apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /"
    #ingress.bluemix.net/rewrite-path: "serviceName=tea rewrite=/;serviceName=coffee rewrite=/"
  name: cafe
  namespace: '${ parameters.namespace }'
spec:
  rules:
  - host: '${ parameters.host }'
    http:
      paths:
      - path: /tea
        backend:
          serviceName: tea
          servicePort: 80
      - path: /others
        backend:
          serviceName: coffee
          servicePort: 80
